<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="6" hostname="KiwiTechs-Mac-mini-4.local" name="testModules.LoginTests" tests="25" failures="2" timestamp="04 Oct 2018 07:28:58 GMT" time="582.177" errors="0">
  <testcase name="wrongUsername" time="20.110" classname="testModules.LoginTests"/>
  <testcase name="offlineLoginDiffUser" time="29.434" classname="testModules.LoginTests"/>
  <testcase name="logOutUsernameCheck" time="6.337" classname="testModules.LoginTests"/>
  <testcase name="checkLogin" time="8.496" classname="testModules.LoginTests"/>
  <testcase name="positiveLogin" time="29.310" classname="testModules.LoginTests"/>
  <testcase name="stringVisiblity" time="15.243" classname="testModules.LoginTests"/>
  <testcase name="wrongPassword" time="18.965" classname="testModules.LoginTests"/>
  <testcase name="loginElementsDisplay" time="13.674" classname="testModules.LoginTests"/>
  <testcase name="offlineLogin" time="43.576" classname="testModules.LoginTests"/>
  <testcase name="passwordInCaps" time="60.457" classname="testModules.LoginTests">
    <skipped/>
  </testcase> <!-- passwordInCaps -->
  <testcase name="dismissKeyboard" time="9.777" classname="testModules.LoginTests">
    <skipped/>
  </testcase> <!-- dismissKeyboard -->
  <testcase name="noPassword" time="12.326" classname="testModules.LoginTests"/>
  <testcase name="wrongUserAndPass" time="19.775" classname="testModules.LoginTests"/>
  <testcase name="TermsAndCondOff" time="22.647" classname="testModules.LoginTests"/>
  <testcase name="noUsername" time="27.139" classname="testModules.LoginTests"/>
  <testcase name="dismissKeyboard" time="7.268" classname="testModules.LoginTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at testModules.LoginTests.dismissKeyboard(LoginTests.java:333)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- dismissKeyboard -->
  <testcase name="positiveLogin" time="38.126" classname="testModules.LoginTests">
    <skipped/>
  </testcase> <!-- positiveLogin -->
  <testcase name="noUserAndPass" time="13.784" classname="testModules.LoginTests"/>
  <testcase name="passwordInCaps" time="51.681" classname="testModules.LoginTests">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at testModules.LoginTests.passwordInCaps(LoginTests.java:313)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- passwordInCaps -->
  <testcase name="forgotPasswordPage" time="28.242" classname="testModules.LoginTests"/>
  <testcase name="TermsAndCondLink" time="15.572" classname="testModules.LoginTests"/>
  <testcase name="forgotPasswordCancel" time="6.994" classname="testModules.LoginTests"/>
  <testcase name="wrongPassword" time="32.363" classname="testModules.LoginTests">
    <skipped/>
  </testcase> <!-- wrongPassword -->
  <testcase name="passwordInCaps" time="42.792" classname="testModules.LoginTests">
    <skipped/>
  </testcase> <!-- passwordInCaps -->
  <testcase name="dismissKeyboard" time="8.089" classname="testModules.LoginTests">
    <skipped/>
  </testcase> <!-- dismissKeyboard -->
</testsuite> <!-- testModules.LoginTests -->
